- type: log
  enabled: true
  multiline:
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        negate: true
        match: after
  paths:
    - /var/log/filebeat/filebeat
  fields:
    "log_topic": "log_filebeat"