---

- name: copy pipeline.yml to host
  copy: 
    src: "{{pipeline_yml}}"
    dest: /etc/logstash/pipelines.yml
    owner: root
    group: root
    backup: yes
    mode: 0777
    
  
- name: copy pipeline conf to host
  copy:
    src: "{{pipeline_conf_name}}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    backup: yes
    mode: 0777
    


