---

- name: copy logstash.yml to /etc/logstash/
  copy: 
    src: logstash.yml
    dest: /etc/logstash/
    owner: root
    group: root
    backup: yes
    mode: 01777
    
  
- name: restart logstash
  service:
    name: logstash
    state: restarted


