---
- name: download rpm to target dir
  shell: cd /usr/local && curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.5.4-x86_64.rpm

- name: install filebeat
  shell: rpm -ivh /usr/local/filebeat-6.5.4-x86_64.rpm

- name: create configs dir
  shell: mkdir /etc/filebeat/configs

- name: copy filebeat.yml to hosts
  vars:
    hostname: "{{ ansible_facts['nodename'] }}"
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    backup: yes
    