# Settings file in YAML
# ------------ Data path ------------------
path.data: /data0/logstash/data

# ------------ pipeline -------------------
config.reload.automatic: true

# ------------ Metrics Settings --------------
http.host: "127.0.0.1"

# ------------ Dead-Letter Queue Settings --------------
#dead_letter_queue.enable: true
# Default is path.data/dead_letter_queue
#path.dead_letter_queue: 

# ------------ Debugging Settings --------------
path.logs: /var/log/logstash
#
# ------------ X-Pack Settings (not applicable for OSS build)--------------
# X-Pack Monitoring
# https://www.elastic.co/guide/en/logstash/current/monitoring-logstash.html
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: elastic
xpack.monitoring.elasticsearch.url: ["http://es1:9200", "http://es2:9200","http://es3:9200"]
#xpack.monitoring.elasticsearch.ssl.ca: [ "/path/to/ca.crt" ]
#xpack.monitoring.elasticsearch.ssl.truststore.path: path/to/file
#xpack.monitoring.elasticsearch.ssl.truststore.password: password
#xpack.monitoring.elasticsearch.ssl.keystore.path: /path/to/file
#xpack.monitoring.elasticsearch.ssl.keystore.password: password
#xpack.monitoring.elasticsearch.ssl.verification_mode: certificate
xpack.monitoring.elasticsearch.sniffing: true
xpack.monitoring.collection.interval: 10s
xpack.monitoring.collection.pipeline.details.enabled: true
#

# X-Pack Management
# https://www.elastic.co/guide/en/logstash/current/logstash-centralized-pipeline-management.html
xpack.management.enabled: true
xpack.management.pipeline.id: ["log_logstash","mysqlToES","log_tidb","log_tikv","log_tidbServer","kafkaTokafka","log_es","log_kafka","log_metric_connect"]
xpack.management.elasticsearch.username: elastic
xpack.management.elasticsearch.password: elastic
xpack.management.elasticsearch.url: ["http://172.17.100.21:9200", "http://172.17.100.22:9200","http://172.17.100.23:9200"]
